### ISSUE TITLE
short_introduction expected not matching real outcome

### ISSUE THREAD

**Issue by NickRaw** [python-discord/summer-code-jam-2020-qualifier#6]
So I was working on the short_introduction function and somehow I couldn't get it working.

So I started looking in test_qualifier.py and found out that with two qualifications the amount of words don't work with what's expected.
* In line 55 you want 31 words while the expected string is 28. Using "'I know I'm not stupid,' the man" will work and is longer that 31 characters so you know that the function will return whole words.
* In line 57 you expect "see anything." to return which is 13 characters long but you want 16 characters. I fixed that by just asking for 13 characters

**Comment by SebastiaanZ** [comment]
Hello!

The requirement is to return *at most* the specified number of characters, not exactly the number of characters requested. To make sure the short introduction does not have cut-off words at the end, the requirement asks you to find the rightmost space/newline character you can use as a break-off point so that the short introduction returned is at most `n_characters` long.

If you look at the test case defined on line 55, the only way to do that is by breaking at the space character before `"man"`.

```python
>>> len("'I know I'm not stupid,' the man thought,")
41
>>> len("'I know I'm not stupid,' the man")  # too long
32  # longer than the allowed 31 characters
>>> len("'I know I'm not stupid,' the")
28  # The longest possible string broken on a space/newline character
```

**Comment by NickRaw** [comment]
Aha okay. It's more clear now. Thanks!
